### PR TITLE
fix: contrast color for overlay labels based on node color

### PR DESCRIPTION
**Pull request by PurwaShrivastava**

### CODE REVIEW

**Comment by T-Wizard** [comment]
I think that a proper fix should be to find the correct parent (the one that has the overlay) in incrementColor
I do not see how this would work well when the overlay covers cells with different colors

**Comment by PurwaShrivastava** [comment]
> I think that a proper fix should be to find the correct parent (the one that has the overlay) in incrementColor I do not see how this would work well when the overlay covers cells with different colors

I had looked into this scenario, which is specific to when we have three dimensions and want the headers OFF, in that case header nodes are shown as overlay and these header nodes doesn't have a sumColor value in the incrementColor method as they are the parent nodes. This is the very reason the bug is caused and overlay labels are shown white always as the headers just have one color that is #F2F2F2. So that approach doesn't work here and thus I have to get the nodeColor in this case and get a contrasting color to it in the overlayNodes.

**Comment by T-Wizard** [comment]
> > I think that a proper fix should be to find the correct parent (the one that has the overlay) in incrementColor I do not see how this would work well when the overlay covers cells with different colors
> 
> I had looked into this scenario, which is specific to when we have three dimensions and want the headers OFF, in that case header nodes are shown as overlay and these header nodes doesn't have a sumColor value in the incrementColor method as they are the parent nodes. This is the very reason the bug is caused and overlay labels are shown white always as the headers just have one color that is #F2F2F2. So that approach doesn't work here and thus I have to get the nodeColor in this case and get a contrasting color to it in the overlayNodes.

yes, but I still think the fix should be in incrementColor to make it add up and set sumColor on the correct level.

**Comment by PurwaShrivastava** [comment]
> > > I think that a proper fix should be to find the correct parent (the one that has the overlay) in incrementColor I do not see how this would work well when the overlay covers cells with different colors
> > 
> > 
> > I had looked into this scenario, which is specific to when we have three dimensions and want the headers OFF, in that case header nodes are shown as overlay and these header nodes doesn't have a sumColor value in the incrementColor method as they are the parent nodes. This is the very reason the bug is caused and overlay labels are shown white always as the headers just have one color that is #F2F2F2. So that approach doesn't work here and thus I have to get the nodeColor in this case and get a contrasting color to it in the overlayNodes.
> 
> yes, but I still think the fix should be in incrementColor to make it add up and set sumColor on the correct level.

I have already tried that and the sum always comes to be rgb (242, 242, 242) which is same as #F2F2F2 and then the problem remains that the contrasting color is WHITE.

**Comment by PurwaShrivastava** [comment]
Fixed in another PR.

**Pull request closed without merging**
