### PR TITLE
fix: text wrapping for leaf labels and values

### PR DESCRIPTION
**Pull request by PurwaShrivastava**

### CODE REVIEW

**Review by pernyl — COMMENTED** [review]
Is test/rendering/baselines/multi-scenario-4-baseline.png and test/rendering/baselines/multi-scenario-5-baseline.png correct?

It looks like some of the overlay labels still overlap? Is that something that is included in this change? 

Also just so that you are aware. It is possible to use Tobias script to update the rendering tests.

**Comment by T-Wizard** [comment]
From the update baselines
it looks for when there is only space for one line of text
this change makes it only show the cell value and not the cell label. I think that is wrong

**Comment by PurwaShrivastava** [comment]
> Is test/rendering/baselines/multi-scenario-4-baseline.png and test/rendering/baselines/multi-scenario-5-baseline.png correct?
> 
> It looks like some of the overlay labels still overlap? Is that something that is included in this change?
> 
> Also just so that you are aware. It is possible to use Tobias github action script to update the rendering tests.

These were generated locally, when I used yarn run test:rendering, and this fix dosn't include overlay labels, its only for  labels and values in a tree node. So the overlay labels are still the same way.

**Comment by PurwaShrivastava** [comment]
> From the update baselines it looks for when there is only space for one line of text this change makes it only show the cell value and not the cell label. I think that is wrong (see: dover in [multi-scenario-2-baseline.png](https://github.com/qlik-oss/sn-treemap/pull/107/files#diff-5b29e08b427d5a2a36fd429cd70bb982056c7bce885415075c8485cd6cd5eb08))

It is the same way the old treemap works : both are identical now, when it comes to showing the tree node labels & values : for Dover its hows only value if value labels are toggled ON.
Attached is a screenshot :
Screenshot 2023-01-24 at 16 05 15

**Comment by T-Wizard** [comment]
> It is the same way the old treemap works

OK

**Review by T-Wizard — APPROVED** [review]

**Pull request merged**
